### ISSUE TITLE
Game crashed while initializing - MMDLibRegisterBlockTypes

### ISSUE THREAD

**Issue by DustinDigitaria** [MinecraftModDevelopmentMods/MMDLib#42]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BaseMetals (BaseMetals-1.12-2.5.0-beta6.280.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 5/30/19 12:52 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mcmoddev/lib/events/MMDLibRegisterBlockTypes
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mcmoddev.lib.events.MMDLibRegisterBlockTypes
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.SecurityException: class "com.mcmoddev.lib.events.MMDLibRegisterBlockTypes"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 271115784 bytes (258 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2823 Optifine OptiFine_1.12.2_HD_U_E3 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                        | Signature                                |
	|:----- |:--------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft             | 1.12.2            | minecraft.jar                                 | None                                     |
	| LC    | mcp                   | 9.42              | minecraft.jar                                 | None                                     |
	| LC    | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2823.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                 | 14.23.5.2823      | forge-1.12.2-14.23.5.2823.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | quark                 | r1.5-146          | Quark-r1.5-146.jar                            | None                                     |
	| LC    | autoreglib            | 1.3-26            | AutoRegLib-1.3-26.jar                         | None                                     |
	| LC    | basemetals            | 2.5.0-beta6       | BaseMetals-1.12-2.5.0-beta6.280.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| L     | mmdlib                | 1.0.0-rc2         | MMDLib-1.12-1.0.0-rc2.36.jar                  | None                                     |
	| L     | baseminerals          | 2.5.0-rc2         | BaseMinerals-1.12-2.5.0-rc2.69.jar            | None                                     |
	| L     | betterslabsmod        | 0.0.7             | Better+Slabs+Mod+[0.0.7].jar                  | None                                     |
	| L     | bibliocraft           | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| L     | biomesoplenty         | 7.0.1.2419        | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar | None                                     |
	| L     | bookshelf             | 2.3.577           | Bookshelf-1.12.2-2.3.577.jar                  | None                                     |
	| L     | cfm                   | 6.2.1             | cfm-6.2.1-mc1.12.2.jar                        | None                                     |
	| L     | codechickenlib        | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | None                                     |
	| L     | cxlibrary             | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                    | None                                     |
	| L     | eplus                 | 5.0.177           | EnchantingPlus-1.12.2-5.0.177.jar             | None                                     |
	| L     | endergetic            | 0.0.1             | endergetic-0.0.1.jar                          | None                                     |
	| L     | modernmetals          | 2.5.0-rc2         | ModernMetals-1.12-2.5.0-rc2.152.jar           | None                                     |
	| L     | endmetals             | 1.2.0-rc2         | EndMetals-1.12-1.2.0-rc2.67.jar               | None                                     |
	| L     | forgemultipartcbe     | 2.4.0.54          | ForgeMultipart-1.12.2-2.4.0.54-universal.jar  | None                                     |
	| L     | microblockcbe         | 2.4.0.54          | ForgeMultipart-1.12.2-2.4.0.54-universal.jar  | None                                     |
	| L     | minecraftmultipartcbe | 2.4.0.54          | ForgeMultipart-1.12.2-2.4.0.54-universal.jar  | None                                     |
	| L     | ghostsexplosives      | 2.3.0 - MC 1.12.2 | Ghost's+Explosives+2.3.0+-+MC1.12.2.jar       | None                                     |
	| L     | malisiscore           | 1.12.2-6.4.0      | MalisisCore-1.12.2.jar                        | None                                     |
	| L     | malisisdoors          | 1.12.2-7.3.0      | MalisisDoors-Mod-1.12.2.jar                   | None                                     |
	| L     | mcjtylib_ng           | 3.0.5             | mcjtylib-1.12-3.0.5.jar                       | None                                     |
	| L     | modernlamps           | 1.0.3             | Modern-Lights-Mod-1.12.jar                    | None                                     |
	| L     | morecraft             | 3.2b2             | MoreCraft-Mod-1.12.2.jar                      | None                                     |
	| L     | nethermetals          | 1.2.0-rc2         | NetherMetals-1.12-1.2.0-rc2.76.jar            | None                                     |
	| L     | notenoughwands        | 1.7.1             | notenoughwands-1.12-1.7.1.jar                 | None                                     |
	| L     | elevatorid            | 1.3.5             | OpenBlocks-Elevator-Mod-1.12.2.jar            | None                                     |
	| L     | orespawn              | 3.3.0             | OreSpawn-1.12-3.3.0.155.jar                   | None                                     |
	| L     | shetiphiancore        | 3.5.9             | shetiphiancore-1.12.0-3.5.9.jar               | None                                     |
	| L     | platforms             | 1.4.6             | platforms-1.12.0-1.4.6.jar                    | None                                     |
	| L     | quarkoddities         | 1                 | QuarkOddities-1.12.2.jar                      | None                                     |
	| L     | railcraft             | 12.0.0            | railcraft-12.0.0.jar                          | None                                     |
	| L     | rustic                | 1.0.15            | rustic-1.0.15.jar                             | None                                     |
	| L     | signbutton            | 1.0.1             | SignButton-1.12.2-1.0.1.jar                   | None                                     |
	| L     | stairs                | 1.12.2-b18        | Stairs-1.12.2-b18.jar                         | None                                     |
	| L     | treechopper           | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| L     | wrcbe                 | 2.3.1             | WR-CBE-1.12.2-2.3.1.30-universal.jar          | None                                     |
	| L     | xaerominimap          | 1.16.2            | Xaeros_Minimap_1.16.2_Forge_1.12.jar          | None                                     |
	| L     | corail_pillar         | 4.2.1             | corail_pillar-4.2.1-1.12.jar                  | None                                     |

	Loaded coremods (and transformers): 
BaseMetals (BaseMetals-1.12-2.5.0-beta6.280.jar)
  
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.677.257' Renderer: 'Radeon RX 580 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2823
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 1400 Quad-Core Processor

**Comment by jriwanek** [comment]
Update your version of basemetals.
