### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MMDLib (mmdlib)

### ISSUE THREAD

**Issue by dd957** [MinecraftModDevelopmentMods/MMDLib#46]
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Stat of type "core": Default Material does not have default stats for said type. Please add default-values to the default material "unknown" first.
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:986)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:242)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:210)
	at com.mcmoddev.basemetals.integration.plugins.BMeConstructsArmory.lambda$materialRegistration$1(BMeConstructsArmory.java:47)
	at com.mcmoddev.basemetals.integration.plugins.BMeConstructsArmory$$Lambda$1496/1058397727.accept(Unknown Source)
[latest.log](https://github.com/MinecraftModDevelopmentMods/MMDLib/files/3364546/latest.log)

**Comment by dshadowwolf** [comment]
closing as a copy of #41
