### ISSUE TITLE
Everytime I get into minecraft I get this crash

### ISSUE THREAD

**Issue by DrDestroyerr** [MinecraftModDevelopmentMods/MMDLib#65]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/mcmoddev/lib/events/MMDLibRegisterBlockTypes
Exit Code: -1

I'm trying to use the Spartan Weapons/Shields and the Base metals/minerals and every time I join the game crashes and I get this error message

**Comment by DrDestroyerr** [comment]
I'm gonna try downloading a different version of forge and see if it works

**Comment by KiriCattus** [comment]
Can we have a full crash log to help find the cause, although I would assume another mod is looking for something in an older or newer version of MMDLib and has not setup dependency section properly.

Please upload the crash log to [pastebin](https://pastebin.com)

**Comment by DrDestroyerr** [comment]
Yup here is the full crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Quark Plugin (Quark-r1.6-178.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ThiccEntities Plugin (thiccentities-1.4.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 2/26/21 11:27 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mcmoddev/lib/events/MMDLibRegisterBlockTypes
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mcmoddev.lib.events.MMDLibRegisterBlockTypes
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.SecurityException: class "com.mcmoddev.lib.events.MMDLibRegisterBlockTypes"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333169096 bytes (317 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version        | Source                                        | Signature                                |
	|:----- |:------------------ |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft          | 1.12.2         | minecraft.jar                                 | None                                     |
	| LC    | mcp                | 9.42           | minecraft.jar                                 | None                                     |
	| LC    | FML                | 8.0.99.99      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge              | 14.23.5.2854   | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | jei                | 4.16.1.301     | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LC    | quark              | r1.6-178       | Quark-r1.6-178.jar                            | None                                     |
	| LC    | autoreglib         | 1.3-32         | AutoRegLib-1.3-32.jar                         | None                                     |
	| LC    | basemetals         | 2.5.0-beta7    | BaseMetals-1.12-2.5.0-beta7.311.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| L     | mmdlib             | 1.0.0-rc2      | MMDLib-1.12-1.0.0-rc2.36(1).jar               | None                                     |
	| L     | baseminerals       | 2.5.0-rc2      | BaseMinerals-1.12-2.5.0-rc2.69.jar            | None                                     |
	| L     | forgelin           | 1.8.4          | Forgelin-1.8.4.jar                            | None                                     |
	| L     | betterfoliage      | 2.3.1          | BetterFoliage-MC1.12-2.3.1.jar                | None                                     |
	| L     | biomesoplenty      | 7.0.1.2444     | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| L     | customspawner      | 3.11.4         | CustomMobSpawner-3.11.5.jar                   | None                                     |
	| L     | llibrary           | 1.7.20         | llibrary-1.7.20-1.12.2.jar                    | None                                     |
	| L     | fossil             | 8.0.5          | fossilsarcheology-8.0.5.jar                   | None                                     |
	| L     | orespawn           | 3.3.1          | OreSpawn-1.12-3.3.1.179.jar                   | None                                     |
	| L     | potioncore         | 1.9_for_1.12.2 | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
	| L     | prehistoricspawns  | 1.0            | prehistoricspawns-1.1.jar                     | None                                     |
	| L     | somanyenchantments | 0.5.0          | SoManyEnchantments-0.5.0.jar                  | None                                     |
	| L     | spartanweaponry    | beta 1.3.8     | SpartanWeaponry-1.12.2-beta-1.3.8.jar         | None                                     |
	| L     | spartanbm          | 0.3            | spartanbm-0.3.jar                             | None                                     |
	| L     | spartanshields     | 1.5.4          | SpartanShields-1.12.2-1.5.4.jar               | None                                     |
	| L     | thiccentities      | GRADLE:VERSION | thiccentities-1.4.jar                         | None                                     |
	| L     | orelib             | 3.6.0.1        | OreLib-1.12.2-3.6.0.1.jar                     | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Quark Plugin (Quark-r1.6-178.jar)
  vazkii.quark.base.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
ThiccEntities Plugin (thiccentities-1.4.jar)
  wiresegal.thicc.asm.ThiccAsmTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 460.93' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.93, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by DrDestroyerr** [comment]
Here it is
https://pastebin.com/qHP47vEq

**Comment by KiriCattus** [comment]
Did you download MMDLib, Base Metals and MMD OreSpawn from curseforge by chance? You're using some older builds from the logs you've shown

**Comment by DrDestroyerr** [comment]
Yes I did I thought those were the newest versions for 1.12.2 but I can look again

**Comment by DrDestroyerr** [comment]
Okay its working now I guess I downloaded the older versions, Thank you!
